In [102]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

In [103]:
# Hàm sử dụng thư viện iris.data
file_name = 'iris.data'
df = pd.read_csv(file_name)
print(df.columns)
print(df.head(5))

Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')
   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa


In [104]:
a = df.values
print(a[:5])

[[4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']
 [5.4 3.9 1.7 0.4 'Iris-setosa']]


In [105]:
X = a[:, [0, 1, 2, 3]]
print(X[:5])
y = a[:, [4]]
print(y[:5])

[[4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]]
[['Iris-setosa']
 ['Iris-setosa']
 ['Iris-setosa']
 ['Iris-setosa']
 ['Iris-setosa']]


In [106]:
# Đổi phần tử sang từ 0-1
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
y = LE.fit_transform(y)
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]


C:\Users\nguyn\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [107]:
print(len(X))
print(len(y))
z= list(zip(X,y))
print(z)

149
149
[(array([4.9, 3.0, 1.4, 0.2], dtype=object), 0), (array([4.7, 3.2, 1.3, 0.2], dtype=object), 0), (array([4.6, 3.1, 1.5, 0.2], dtype=object), 0), (array([5.0, 3.6, 1.4, 0.2], dtype=object), 0), (array([5.4, 3.9, 1.7, 0.4], dtype=object), 0), (array([4.6, 3.4, 1.4, 0.3], dtype=object), 0), (array([5.0, 3.4, 1.5, 0.2], dtype=object), 0), (array([4.4, 2.9, 1.4, 0.2], dtype=object), 0), (array([4.9, 3.1, 1.5, 0.1], dtype=object), 0), (array([5.4, 3.7, 1.5, 0.2], dtype=object), 0), (array([4.8, 3.4, 1.6, 0.2], dtype=object), 0), (array([4.8, 3.0, 1.4, 0.1], dtype=object), 0), (array([4.3, 3.0, 1.1, 0.1], dtype=object), 0), (array([5.8, 4.0, 1.2, 0.2], dtype=object), 0), (array([5.7, 4.4, 1.5, 0.4], dtype=object), 0), (array([5.4, 3.9, 1.3, 0.4], dtype=object), 0), (array([5.1, 3.5, 1.4, 0.3], dtype=object), 0), (array([5.7, 3.8, 1.7, 0.3], dtype=object), 0), (array([5.1, 3.8, 1.5, 0.3], dtype=object), 0), (array([5.4, 3.4, 1.7, 0.2], dtype=object), 0), (array([5.1, 3.7, 1.5, 0.4], dt

In [108]:
x1=[6.3,3.4,5.6,2.4]

In [109]:
a= np.array(x1)
for i in range(len(z)):
    b= np.array(z[i][0])
    dist = np.linalg.norm(a-b)
    z[i]=z[i]+(dist,)
print(z)
z.sort(key=lambda x:x[2])

[(array([4.9, 3.0, 1.4, 0.2], dtype=object), 0, 4.959838707054897), (array([4.7, 3.2, 1.3, 0.2], dtype=object), 0, 5.0921508225896055), (array([4.6, 3.1, 1.5, 0.2], dtype=object), 0, 4.962862077471023), (array([5.0, 3.6, 1.4, 0.2], dtype=object), 0, 4.920365840057017), (array([5.4, 3.9, 1.7, 0.4], dtype=object), 0, 4.502221673796171), (array([4.6, 3.4, 1.4, 0.3], dtype=object), 0, 4.993996395673508), (array([5.0, 3.4, 1.5, 0.2], dtype=object), 0, 4.831148931672465), (array([4.4, 2.9, 1.4, 0.2], dtype=object), 0, 5.132250968142536), (array([4.9, 3.1, 1.5, 0.1], dtype=object), 0, 4.914264950122245), (array([5.4, 3.7, 1.5, 0.2], dtype=object), 0, 4.748684028233506), (array([4.8, 3.4, 1.6, 0.2], dtype=object), 0, 4.805205510693585), (array([4.8, 3.0, 1.4, 0.1], dtype=object), 0, 5.033885179461287), (array([4.3, 3.0, 1.1, 0.1], dtype=object), 0, 5.449770637375485), (array([5.8, 4.0, 1.2, 0.2], dtype=object), 0, 4.980963762164908), (array([5.7, 4.4, 1.5, 0.4], dtype=object), 0, 4.70850294679

In [110]:
print("after sort")
print(z)
count=0
k = 100
for i in range(k):
    count+=(z[i][1])
print("\n")
print("- - Result - - ",count/k)

after sort
[(array([6.3, 3.4, 5.6, 2.4], dtype=object), 2, 0.0), (array([6.2, 3.4, 5.4, 2.3], dtype=object), 2, 0.2449489742783171), (array([6.4, 3.2, 5.3, 2.3], dtype=object), 2, 0.3872983346207416), (array([6.3, 3.3, 6.0, 2.5], dtype=object), 2, 0.42426406871192884), (array([6.7, 3.3, 5.7, 2.5], dtype=object), 2, 0.43588989435406783), (array([6.7, 3.1, 5.6, 2.4], dtype=object), 2, 0.5000000000000001), (array([6.7, 3.3, 5.7, 2.1], dtype=object), 2, 0.5196152422706635), (array([6.5, 3.0, 5.8, 2.2], dtype=object), 2, 0.529150262212918), (array([6.8, 3.2, 5.9, 2.3], dtype=object), 2, 0.62449979983984), (array([6.4, 2.8, 5.6, 2.2], dtype=object), 2, 0.640312423743285), (array([6.9, 3.2, 5.7, 2.3], dtype=object), 2, 0.6480740698407865), (array([6.4, 2.8, 5.6, 2.1], dtype=object), 2, 0.6782329983125269), (array([6.4, 3.1, 5.5, 1.8], dtype=object), 2, 0.6855654600401042), (array([6.7, 3.0, 5.2, 2.3], dtype=object), 2, 0.6999999999999998), (array([6.5, 3.2, 5.1, 2.0], dtype=object), 2, 0.7), 