In [ ]:
#Thuật toán sử dụng
# Logistic Regression(Hồi quy tuyến tính)
# Decision Tree(Cây)
# Multinomial NB(Đa thức NB)
# SVM

In [54]:
import pandas as pd
import numpy as np

In [55]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [56]:
dataset = pd.read_csv('Data/weather.csv')
print ("Total number of rows in dataset: {}\n".format(len(dataset)))
print(dataset.head())

Total number of rows in dataset: 21

   Day  Month  Year  Humidity  Max Temperature  Min Temperature  Rainfall  \
0    1     12  2020        77             26.7             12.9         0   
1    2     12  2020        76             26.0             12.9         0   
2    3     12  2020        73             27.5             14.5         0   
3    4     12  2020        71             27.2             15.8         0   
4    5     12  2020        75             27.8             15.4         0   

   Sea Level Pressure  Sunshine  Wind Speed  Cloud  
0              1016.9       8.4         0.0      0  
1              1016.4       8.4         0.0      0  
2              1014.8       7.8         2.0      1  
3              1015.9       6.4         5.0      1  
4              1016.1       8.0         3.5      1  


In [57]:
features = ['Day','Month','Year','Humidity','Max Temperature','Min Temperature',
            'Rainfall','Sea Level Pressure','Sunshine','Wind Speed']
target = 'Cloud'

x_train, x_test, y_train, y_test = train_test_split(dataset[features], dataset[target],
                                                    train_size=0.7, test_size=0.3, shuffle=False)

In [58]:
print("X_train: {}, Y_train: {}".format(len(x_train), len(x_test)))
print("X_train: {}, Y_train: {}".format(len(y_train), len(y_test)))

X_train: 14, Y_train: 7
X_train: 14, Y_train: 7


In [59]:
model = MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)
model.fit(x_train, y_train)

MultinomialNB()

In [60]:
print("Showing Performance Metrics for Naive Bayes Multinomial\n")
print ("Training Accuracy: {}".format(model.score(x_train, y_train)))
predicted = model.predict(x_test)
print ("Testing Accuracy: {}".format(accuracy_score(y_test, predicted)))

Showing Performance Metrics for Naive Bayes Multinomial

Training Accuracy: 0.9285714285714286
Testing Accuracy: 1.0


In [71]:
print("Cross Validation Accuracy: \n")
cv_accuracy = cross_val_score(estimator=model, X=x_train, y=y_train, cv=9)
print("Accuracy using 10 folds: ")
print(cv_accuracy)

Cross Validation Accuracy: 

Accuracy using 10 folds: 
[1.  0.5 1.  1.  0.5 1.  1.  1.  0. ]


C:\Users\USER\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 5 members, which is less than n_splits=9.
  warnings.warn(("The least populated class in y has only %d"


In [72]:
print("Mean accuracy: {}".format(cv_accuracy.mean()))
print("Standard Deviation: {}".format(cv_accuracy.std()))

Mean accuracy: 0.7777777777777778
Standard Deviation: 0.3424674446093876


In [66]:
print("Confusion Matrix for Naive Bayes Multinomial\n")
labels = [0, 1, 2]
cm = confusion_matrix(y_test, predicted, labels=labels)
print(cm)

Confusion Matrix for Naive Bayes Multinomial

[[7 0 0]
 [0 0 0]
 [0 0 0]]


In [67]:
print('Precision, Recall and f-1 Scores for Naive Bayes Multinomial\n')
print(classification_report(y_test, predicted))

Precision, Recall and f-1 Scores for Naive Bayes Multinomial

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7

    accuracy                           1.00         7
   macro avg       1.00      1.00      1.00         7
weighted avg       1.00      1.00      1.00         7

